name: 'platformOS/CompareSnaphosts'
description: compare-snapshots
inputs:
  base:
    required: true
    description: base branch for PR
  project-name:
    description: 'name of a project'
    required: false
  test-name:
    description: 'test name'
    required: true
  slack-webhook-url:
    description: 'slack webhook url'
    required: true
  before:
    required: false
  after:
    required: false
  skip:
    required: false
  npm-prefix:
    required: false
    default: "."
runs:
  using: "composite"
  steps:

      - name: before ${{ inputs.test-name }}
        if: ${{ inputs.before && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.before }}

      - name: run ${{ inputs.test-name }}
        env:
          REPORT_TYPE: ${{ inputs.test-name }}
        if: ${{ !inputs.skip }}
        shell: sh
        run: |
          set -e
          npm run ${{ inputs.test-name }} --prefix ${{ inputs.npm-prefix }} 

      - name: compare screenshots
        id: diff-test
        if: ${{ !inputs.skip }}
        shell: sh
        run: |
          set -eu
          npx testcafe-blink-diff \
            ./tests/visual-tests/snapshots/${{ env.resolution }}/Snapshots \
            ./tests/visual-tests/generated/${{ env.resolution }} \
            --compare base-${{ env.resolution }}{{ project }}:actual-${{ env.resolution }}{{ project }} --threshold 5
        env:
          project: ${{ inputs.project-name && `-${inputs.project-name}` || '' }}

      - name: deploy diff report
        id: deploy-diff-rep
        if: success() || failure()
        shell: sh
        run: |
          set -eu
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')

          cd ./tests/visual-tests/generated/${{ env.resolution }}

          PAGE_DIR=app/views/pages
          IMAGE_DIR=app/assets/images/$TIMESTAMP

          mkdir -p $PAGE_DIR $IMAGE_DIR

          mv Snapshot* $IMAGE_DIR

          sed -i "s/Snapshot/\/assets\/images\/$TIMESTAMP\/Snapshot/g" index.html
          sed 's/body {.*}/html {height: 100%;} body { font-family: Helvetica; height: 100%; overflow: scroll }/' index.html -i
          mv index.html $PAGE_DIR/$TIMESTAMP.liquid

          # ci
          MPKIT_URL=$UPLOAD_HOST
          pos-cli deploy -p

          echo REPORT_URL=$MPKIT_URL/$TIMESTAMP >> $GITHUB_OUTPUT

      - name: Send notification to Slack
        id: notify-slack
        if: success() || failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "test-reports",
              "text": "Visual regression tests",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "testcafe blink diff visual regression tests for ${{ env.resolution }} resolution"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Actor:*\n${{ github.actor }}\n"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View action run>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.result_icon }} <${{ steps.deploy-diff-rep.outputs.REPORT_URL }}|View test report>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          result_icon: ${{ steps.diff-test.conclusion == 'success' && ':white_check_mark:' || ':x:' }}

      - name: after ${{ inputs.test-name }}
        if: ${{ inputs.after && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.after }}

      - name: summary
        if: ${{ !inputs.skip && always() }}
        shell: sh
        run: |
          REPORT_TYPE=${{ inputs.test-name }}
          echo "### FAILED $REPORT_TYPE tests report -> ${{ steps.deploy-diff-rep.outputs.REPORT_URL }}" >> $GITHUB_STEP_SUMMARY

      - name: skip ${{ inputs.test-name }}
        if: ${{ !!inputs.skip }}
        shell: sh
        run: echo skipping ${{ inputs.test-name }}
