name: 'platformOS/CompareSnaphosts'
description: compare-snapshots
inputs:
  base:
    required: true
    description: base branch for PR
  test-name:
    description: 'test name'
    required: true
  before:
    required: false
  after:
    required: false
  skip:
    required: false
  npm-prefix:
    description: 'name of a directory with test-specific dependencies, e.g. "tests"'
    required: false
    default: "."
  resolution:
    description: resolution of the screen
    required: true
outputs:
  desktop-diff-conclusion:
    description: 'conclusion of the step'
    value: ${{ steps.get-conclusion.outputs.desktop-diff-conclusion }}
  desktop-diff-report-url:
    description: 'url of desktop diff report'
    value: ${{ steps.deploy-diff-report.outputs.desktop-diff-report-url }}
  mobile-diff-conclusion:
    description: 'conclusion of the step'
    value: ${{ steps.get-conclusion.outputs.mobile-diff-conclusion }}
  mobile-diff-report-url:
    description: 'url of desktop diff report'
    value: ${{ steps.deploy-diff-report.outputs.mobile-diff-report-url }}
  tablet-diff-conclusion:
    description: 'conclusion of the step'
    value: ${{ steps.get-conclusion.outputs.tablet-diff-conclusion }}
  tablet-diff-report-url:
    description: 'url of desktop diff report'
    value: ${{ steps.deploy-diff-report.outputs.tablet-diff-report-url }}

runs:
  using: "composite"
  steps:

      - name: before ${{ inputs.test-name }}
        if: ${{ inputs.before && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.before }}

      - name: run ${{ inputs.test-name }}
        if: success() || failure()
        env:
          REPORT_TYPE: ${{ inputs.test-name }}
        shell: sh
        run: |
          set -e
          npm run ${{ inputs.test-name }} --prefix ${{ inputs.npm-prefix }} 

      - name: compare screenshots
        id: diff-test
        if: success() || failure()
        shell: sh
        run: |
          set -eu
          npx testcafe-blink-diff \
            ./tests/visual-tests/snapshots/${{ inputs.resolution }}/Snapshots \
            ./tests/visual-tests/generated/${{ inputs.resolution }} \
            --compare base-${{ inputs.resolution }}:actual-${{ inputs.resolution }} --threshold 5

      - name: pass the conclusion of the previous step to output context
        id: get-conclusion
        if: success() || failure()
        shell: sh
        run: |
          set -eu
          echo "${{ inputs.resolution }}-diff-conclusion=${{ steps.diff-test.conclusion }}" >> $GITHUB_OUTPUT

      - name: deploy diff report
        id: deploy-diff-report
        if: success() || failure()
        shell: sh
        run: |
          set -eu
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')

          cd ./tests/visual-tests/generated/${{ inputs.resolution }}

          PAGE_DIR=app/views/pages
          IMAGE_DIR=app/assets/images/$TIMESTAMP

          mkdir -p $PAGE_DIR $IMAGE_DIR

          mv Snapshot* $IMAGE_DIR

          sed -i "s/Snapshot/\/assets\/images\/$TIMESTAMP\/Snapshot/g" index.html
          sed 's/body {.*}/html {height: 100%;} body { font-family: Helvetica; height: 100%; overflow: scroll }/' index.html -i
          mv index.html $PAGE_DIR/$TIMESTAMP.liquid

          # ci
          MPKIT_URL=$UPLOAD_HOST
          pos-cli deploy -p

          echo "${{ inputs.resolution }}-diff-report-url=$MPKIT_URL/$TIMESTAMP" >> $GITHUB_OUTPUT


      - name: after ${{ inputs.test-name }}
        if: ${{ inputs.after && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.after }}

      - name: summary
        if: ${{ !inputs.skip && always() }}
        shell: sh
        run: |
          REPORT_TYPE=${{ inputs.test-name }}
          echo "### FAILED $REPORT_TYPE tests report -> ${{ steps.deploy-diff-rep.outputs.REPORT_URL }}" >> $GITHUB_STEP_SUMMARY

      - name: skip ${{ inputs.test-name }}
        if: ${{ !!inputs.skip }}
        shell: sh
        run: echo skipping ${{ inputs.test-name }}
