name: 'platformOS/CompareSnaphosts'
description: compare-snapshots
inputs:
  base:
    required: true
    description: base branch for PR
  test-name:
    description: 'test name'
    required: true
  slack-webhook-url:
    description: 'slack webhook url'
    required: true
  before:
    required: false
  after:
    required: false
  skip:
    required: false
  npm-prefix:
    required: false
    default: "."
runs:
  using: "composite"
  steps:

      - name: before ${{ inputs.test-name }}
        if: ${{ inputs.before && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.before }}

      - name: run ${{ inputs.test-name }}
        env:
          REPORT_TYPE: ${{ inputs.test-name }}
        if: ${{ !inputs.skip }}
        shell: sh
        run: |
          set -e
          npm run ${{ inputs.test-name }} --prefix ${{ inputs.npm-prefix }}

      - name: compare screenshots
        if: ${{ !inputs.skip }}
        shell: sh
        run: |
          set -e
          npx testcafe-blink-diff ./test/snapshots/Snapshots ./test/visual-tests/generated --compare base:actual --threshold 5 --force

      - name: deploy diff report
        id: deploy-diff-rep
        if: ${{ !inputs.skip }}
        shell: sh
        run: |
          set -eu
          TIMESTAMP=$(date '+%Y%m%d%H%M%S')

          cd ./test/visual-tests/generated

          PAGE_DIR=app/views/pages
          IMAGE_DIR=app/assets/images

          mkdir -p $PAGE_DIR $IMAGE_DIR

          mv Snapshot* $IMAGE_DIR

          sed -i 's/Snapshot/\/assets\/images\/Snapshot/g' index.html
          mv index.html $PAGE_DIR/$TIMESTAMP.liquid

          # ci
          MPKIT_URL=$UPLOAD_HOST
          pos-cli deploy -p

          echo REPORT_URL=$MPKIT_URL/$TIMESTAMP >> $GITHUB_OUTPUT

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "eng-qa",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                      "type": "plain_text",
                      "text": "Visual regression tests",
                      "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Link to test report: ${{ steps.deploy-diff-rep.outputs.REPORT_URL }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }} 

      - name: after ${{ inputs.test-name }}
        if: ${{ inputs.after && !inputs.skip }}
        shell: sh
        run: |
          ${{ inputs.after }}

      - name: summary
        if: ${{ !inputs.skip && always() }}
        shell: sh
        run: |
          REPORT_TYPE=${{ inputs.test-name }}
          echo "### FAILED $REPORT_TYPE tests report -> $UPLOAD_HOST/$REPORT_PATH-$REPORT_TYPE" >> $GITHUB_STEP_SUMMARY

      - name: skip ${{ inputs.test-name }}
        if: ${{ !!inputs.skip }}
        shell: sh
        run: echo skipping ${{ inputs.test-name }}
